name: Register Trained Model in Azure ML

on:
  workflow_dispatch:
    inputs:
      TRAINED_MODEL_STATUS:
        description: "Estado del modelo entrenado"
        required: true
      TRAINED_MODEL_RUN_ID:
        description: "ID del workflow que generó el modelo"
        required: true

env:
  MODEL_NAME: "genesis-model"

jobs:
  register:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.inputs.TRAINED_MODEL_STATUS == 'success' }}
    permissions:
      id-token: write
      contents: read
      actions: read  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      
      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: ./model/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.TRAINED_MODEL_RUN_ID }}

      # ✅ Verificar que el modelo existe
      - name: Verify model exists
        run: |
          ls -la ./model/
          if [ ! -f "./model/config.json" ]; then
            echo "❌ Error: Model files not found"
            exit 1
          fi
          echo "✅ Model files found successfully"

      - name: Install Azure ML SDK
        run: pip install azureml-core azureml-mlflow

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72CA7AEE169644A2A6D6EE7D78CEB1A1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68A04A5D3F714FFEAA878BA16F356FDC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6E2B627C9AB541DDB483EB9AA290941A }}

      - name: Install deployment dependencies
        run: pip install -r backend/ml/deployment/requirements.txt

      - name: Run model registration script
        run: python backend/ml/deployment/register_model.py
        env:
          MODEL_NAME: ${{ env.MODEL_NAME }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
