name: Register Trained Model in Azure ML

on:
  workflow_run:
    workflows: ["Train Hugging Face Model"]
    types:
      - completed

env:
  MODEL_NAME: "genesis-model"

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Azure ML SDK
        run: pip install azureml-core azureml-mlflow

      - name: Install deployment dependencies
        run: pip install -r backend/ml/deployment/requirements.txt

      - name: Run model registration script
        run: python backend/ml/deployment/register_model.py
        env:
          MODEL_NAME: ${{ env.MODEL_NAME }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
