# .github/workflows/register-model.yml
name: Register fine-tuned model

on:
  workflow_dispatch:  # lo ejecutas manualmente
  # O puedes añadirlo al final de la pipeline de entrenamiento con `needs`

jobs:
  register:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install azure-ai-ml azure-identity

      - name: Run model registration
        run: python backend/ml/deployment/register_model.py
