# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python Function 2 to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  FUNCTION_FOLDER: 'backend/Function2_GenerateEmbeddings'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install required python modules
        run: |
          cd ${{ env.FUNCTION_FOLDER }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip Function App for deployment
        run: |
          cd ${{ env.FUNCTION_FOLDER }}
          zip -r ../../function2.zip . .python_packages

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE25DE9DBD7449EFB1DD50F49677BDF8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7B3FB93A99CE48979108EEA52CC5FA6D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0A1C1F19D98F4263B608D97EFA208976 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-genesis-rag'
          slot-name: 'Production'
          package: 'function2.zip'
