name: Train Hugging Face Model

on:
  workflow_dispatch:
    inputs:
      BLOB_DATASET_FILENAME:
        description: "Nombre del dataset JSONL en /data"
        required: true

env:
  DATASET_PATH: ./data/${{ github.event.inputs.BLOB_DATASET_FILENAME }}
  HUGGINGFACE_MODEL: "google/flan-t5-base"

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72CA7AEE169644A2A6D6EE7D78CEB1A1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68A04A5D3F714FFEAA878BA16F356FDC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6E2B627C9AB541DDB483EB9AA290941A }}

      - name: Install dependencies
        run: pip install -r backend/ml/training/requirements.txt

      - name: Train model
        run: python backend/ml/training/train_model.py
        env:
          DATASET_PATH: ${{ env.DATASET_PATH }}
          HUGGINGFACE_MODEL: ${{ env.HUGGINGFACE_MODEL }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
