name: Upload Dataset to Azure Blob Storage

on:
  workflow_dispatch:  # Lanzamiento manual

env:
  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  STORAGE_CONTAINER_NAME: datasets
  STORAGE_SAS_TOKEN: ${{ secrets.STORAGE_SAS_TOKEN }} # Token SAS con permisos de escritura
  DATASET_FILE_PATH: ./data/datasetmodel_0_100.csv  # Ajusta la ruta al dataset

jobs:
  upload-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install AzCopy
      run: |
        curl -sL https://aka.ms/downloadazcopy-v10-linux | tar -xz
        sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/

    - name: Upload dataset to Azure Blob Storage
      run: |
        azcopy copy \
          "${{ env.DATASET_FILE_PATH }}" \
          "https://${{ env.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ env.STORAGE_CONTAINER_NAME }}/dataset.jsonl?${{ env.STORAGE_SAS_TOKEN }}" \
          --overwrite=true
