name: Sync Datasets to Azure Blob Storage

on:
  workflow_dispatch:

env:
  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  STORAGE_CONTAINER_NAME: datasets
  STORAGE_SAS_TOKEN: ${{ secrets.STORAGE_SAS_TOKEN }}

jobs:
  sync-and-trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      id-token: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install AzCopy
      run: |
        curl -sL https://aka.ms/downloadazcopy-v10-linux | tar -xz
        sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/

    - name: List blobs using curl and Upload and trigger training for new datasets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ github.repository }}
      run: |
        echo "📥 Listando blobs remotos desde Azure Blob Storage..."

        curl_url="https://${STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${STORAGE_CONTAINER_NAME}?restype=container&comp=list&${STORAGE_SAS_TOKEN}"
        echo "🌐 URL: $curl_url"

        curl -s "$curl_url" > curl_output.xml
        echo "📄 Respuesta XML:"
        cat curl_output.xml

        # Extraer nombres de blobs
        tr '>' '>\n' < curl_output.xml | grep "<Name>" | awk -F'[<>]' '{print $3}' > remote_basenames.txt

        echo "📄 Contenido de remote_basenames.txt:"
        cat -A remote_basenames.txt || echo "❌ No existe o está vacío"

        if [[ ! -s remote_basenames.txt ]]; then
          echo "⚠️ remote_basenames.txt está vacío, se subirán todos los archivos locales"
          touch remote_basenames.txt
        fi

        for file in ./data/*.jsonl; do
          if [[ -f "$file" ]]; then
            filename=$(basename "$file")
            echo "🔍 Checking $filename..."

            if ! grep -Fx -- "$filename" <(tr -d '\r' < remote_basenames.txt); then
              echo "⬆️ Subiendo $filename a Blob Storage..."
              azcopy copy "$file" \
                "https://${STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${STORAGE_CONTAINER_NAME}/$filename?${STORAGE_SAS_TOKEN}" \
                --overwrite=false

              if [ $? -eq 0 ]; then
                echo "✅ Upload exitoso de $filename"
                echo "🚀 Ejecutando workflow de entrenamiento en Azure ML..."
                gh workflow run mlflow_train.yml \
                  --repo "$REPO_NAME" \
                  --field BLOB_DATASET_FILENAME="$filename"
              else
                echo "❌ Error al subir $filename con AzCopy"
              fi
            else
              echo "⏭️ Skipping $filename (ya existe en Blob)"
            fi
          fi
        done
